Vagrant.configure("2") do |config|
  config.vm.define "winbase"
  config.vm.define "uprox"

  config.vm.provider :virtualbox do |vb|
   vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
  end

  # Win 10 base box created by this instruction: http://huestones.co.uk/node/305
  # Box updated to 'Creators Update Fall`2017'
  #
  config.vm.define "winbase" do |winbase|
  winbase.vm.box = "win10"
  winbase.vm.communicator = "winrm"
  winbase.winrm.username = "vagrant"
  winbase.vm.boot_timeout = 600
  winbase.vm.graceful_halt_timeout = 600
	winbase.vm.base_mac = "aabbcc112211"

  winbase.vm.network :forwarded_port, guest: 3389, host: 1289
  winbase.vm.network :forwarded_port, guest: 5985, host: 778, id: "winrm", auto_correct: true
  # winbase.vm.network "public_network",
  #                   ip: "192.168.0.2",
  #                   netmask: "255.255.255.0"
  #
  # winbase.vm.provision "shell", path: "config/provision_winbase.ps1", privileged: true
  end

  # Win 10 uprox box ctreated from Win 10 base box (previous step)
  # Box updated to 'Creators Update Fall`2017'
  # Box packed with U-Prox Free (from official site, from DVD image, not standalone installer)
  # Prepared from Oracle VitrualBox image with Win10 base
  config.vm.define "uprox" do |uprox|
  uprox.vm.box = "win10uprox"
  uprox.vm.network "public_network",
                     ip: "192.168.0.2",
                     netmask: "255.255.255.0"

  uprox.vm.provision "shell",
                      path: "config/provision_uprox_always.ps1",
                      privileged: true,
                      run: "always"
  uprox.vm.provision "shell",
                      path: "config/provision_uprox.ps1",
                      privileged: true
  end

end
